terraform()

pipeline {
     agent any    
    
     stages {
         stage('Terraform Init') {
             steps {
                 sh "terraform init ./Ec2/main.tf"
                    
             }
         }

         stage('Terraform Plan') {
             steps {
                 sh "terraform plan"
                    
             }
         }

         stage('Terraform Apply') {
             steps {
                 sh "terraform apply -auto-approve"
                    
              }
         }
     }
 }
